# GHST Ghost Personality Configuration
# Configuration for ghost AI personalities

# Core ghosts (built-in)
core_ghosts:
  core_ghost:
    name: "Core Assistant"
    specialization: "General AI Assistance"
    personality: "helpful, friendly, knowledgeable"
    enabled: true
    
  system_ghost:
    name: "System Manager"
    specialization: "System Management & Monitoring"
    personality: "efficient, precise, proactive"
    enabled: true

# Ghost behavior settings
behavior:
  # Response style
  response_style: "conversational"  # Options: conversational, technical, concise
  
  # Personality traits
  personality:
    formality: 0.5  # 0=casual, 1=formal
    verbosity: 0.7  # 0=concise, 1=detailed
    creativity: 0.6  # 0=conservative, 1=creative
    
  # Collaboration settings
  collaboration:
    enable_ghost_discussions: true
    max_discussion_rounds: 3
    consensus_threshold: 0.7
    
# Expert ghost settings (loaded from plugins)
expert_ghosts:
  # These are loaded dynamically from expertise branches
  auto_load: true
  max_loaded: 10
  
# Ghost communication
communication:
  # Internal ghost communication
  enable_internal_chat: true
  log_internal_discussions: false
  
  # User interaction
  show_ghost_names: true
  show_specializations: true
  emoji_indicators: true
