name: GHST Dependency & Vulnerability Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run weekly on Monday at 9am UTC
    - cron: '0 9 * * 1'

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety pip-audit
        
    - name: Check for known vulnerabilities with safety
      run: |
        # Check installed packages for known security vulnerabilities
        pip install -r requirements.txt
        safety check --json || echo "Safety check completed with warnings"
        
    - name: Audit dependencies with pip-audit
      run: |
        # Audit Python packages for known vulnerabilities
        pip-audit --requirement requirements.txt || echo "Pip audit completed with warnings"
        
    - name: Check outdated packages
      run: |
        pip list --outdated
